import Genre from "./SubTypes/Genre";
import ProductionCompany from "./SubTypes/ProductionCompany";
import ProductionCountry from "./SubTypes/ProductionCountry";
import SpokenLanguage from "./SubTypes/SpokenLanguage";
import Videos from "./Videos";
import Credits from "./Credits";
import Movies from "./Movies";

type MovieDetails = {
  adult: boolean;
  backdrop_path: string;
  belongs_to_collection?: any;
  budget: number;
  genres?: Genre[];
  genre_ids?: number[];
  homepage: string;
  id: number;
  imdb_id: string;
  original_language: string;
  original_title: string;
  overview: string;
  popularity: number;
  poster_path?: any;
  production_companies?: ProductionCompany[];
  production_countries?: ProductionCountry[];
  release_date: string;
  revenue: number;
  runtime: number;
  spoken_languages?: SpokenLanguage[];
  status: string;
  tagline: string;
  title: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
  videos?: Videos;
  credits?: Credits;
  similar?: Movies;
  trending?: Movies;
};

export default MovieDetails;
